dist: xenial
language: node_js
node_js:
  - "stable"
before_install:
  - npm install
script :
  - npm run-script build
after_success:
  - tar cvf $SCOUTER_PAPER-COMPRESS-NAME build/
  - apt-get install sshpass
  - apt-get install openssh-client
  - echo "$DEMO_DEPLOY_KEY" | tr -d '\r' > $DEMO_DELOY_FILE
  - scp -i $DEMO_DELOY_FILE ./$SCOUTER_PAPER-COMPRESS-NAME $DEMO_SERVER_USER@$DEMO_SERVER_NODE
  - ssh -i $DEMO_DELOY_FILE -T $DEMO_SERVER_USER@$DEMO_SERVER_NODE "/home/ec2-user/deploy.sh $SCOUTER_PAPER-COMPRESS-NAME"
cache:
  directories:
    - "node_modules"
branches:
  only:
    - development
    - master
notifications:
  slack: scouterapm:fJndRYgbQA0uTLXiEqxZJhUU

#: construction_worker:
# job life cycle explain : https://docs.travis-ci.com/user/job-lifecycle/