version: '3.2'
services:
  scouter-paper:
    build :
      context : .
      dockerfile: Dockerfile-Dev
      args:
        - PAPER_VERSION=${PAPER_VERSION}
    image : scouterapm/scouter-paper:${PAPER_VERSION}
    restart : always
    ports:
      - 8080:80